name: CI_CD_SITE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./src/FI.WebAtividadeEntrevista
    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore FI.WebAtividadeEntrevista.sln

      - name: Build
        run: msbuild FI.WebAtividadeEntrevista.sln /p:Configuration=Release /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=${{ github.workspace }}\publish /p:PrecompileBeforePublish=true /p:EnableUpdateable=false

      - name: Zip
        run: compress-archive ${{ github.workspace }}\publish\* ${{ github.workspace }}\app.zip

      - name: Upload App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ github.workspace }}\app.zip



  deploy:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download App Artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "funcao-desafio-site"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_SITE }}
          package: ${{ github.workspace }}\app.zip
